[project]
name = "ai-engineering-codespace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "prelipcean", email = "prelipcean.gheorghe@yahoo.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=3.16.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-engineering-codespace = "ai_engineering_codespace:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
